language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t willvac/boogle-maps-test -f Dockerfile.dev .
    
script:
    - docker run willvac/boogle-maps-test mvn test

after_success:
    - docker build -t willvac/boogle-maps -f Dockerfile.prod .

    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push willvac/boogle-maps


deploy:
    provider: elasticbeanstalk
    region: us-west-1
    app: boogle-maps
    env: BoogleMaps-env
    bucket_name: elasticbeanstalk-us-west-1-414250210524
    bucket_path: boogle-maps
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY