FROM maven:amazoncorretto
WORKDIR /boogle-maps
COPY ./ ./
RUN mvn clean install

FROM amazoncorretto:11
WORKDIR /boogle-maps
COPY --from=0 /boogle-maps/target/boogle-maps-0.0.1-SNAPSHOT.jar ./
CMD ["java","-jar", "boogle-maps-0.0.1-SNAPSHOT.jar"]