apiVersion: v1
kind: Service
metadata:
  name: postgres-pricing-node-port
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31516
  selector:
    component: postgres-pricing
