apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pricing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres-pricing
  template:
    metadata:
      labels:
        component: postgres-pricing
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: pricing-database-persistent-volume-claim
      containers:
        - name: postgres-pricing
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: sa1234
            - name: POSTGRES_USER
              value: sa
            - name: POSTGRES_DB
              value: pricing