apiVersion: v1
kind: Service
metadata:
  name: pricing-service-node-port
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 31515
  selector:
    component: pricing-service
